import type { Metadata } from "next";
import {Montserrat_Alternates, Nabla, Fascinate} from "next/font/google";
import "./globals.css";

const montserratAlternatesSans= Montserrat_Alternates({
  variable: "--font-Montserrat-Alternates-sans",
  weight: "400",
  subsets: ["latin"],
});

const nablaSans= Nabla({
  variable: "--font-Nabla-sans",
  subsets: ["latin"],
});

const fascinateSans= Fascinate({
  variable: "--font-Fascinate-sans",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratAlternatesSans.variable} ${nablaSans.variable} ${fascinateSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

